# compose.yaml
services:
  server:
    image: lamapi-server
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - reseau
    volumes:
      - output_volume:/output
volumes:
  output_volume:
    external: true
networks:
  reseau:
    driver: bridge