# compose.yaml
services:
  # lamar:
  #   image: ghcr.io/microsoft/lamar-benchmark/lamar:latest
  #   container_name: lamar_container
  #   restart: unless-stopped
  #   ports:
  #     - 8086:8086
  #   volumes:
  #     - output_volume:/output
  #   networks:
  #     - reseau
  server:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 5000:5000
    networks:
      - reseau
    volumes:
      - output_volume:/output
  client_web:
    build:
      context: ./python
      dockerfile: Dockerfile2
    container_name: client
    ports:
      - 8080:8080
    volumes:
      - output_volume:/output
    networks:
      - reseau
    # depends_on:
    #   - server
volumes:
  output_volume:
networks:
  reseau:
    driver: bridge