# compose.yaml
services:
  server:
    image: python:3.10-slim
    container_name: server
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_IMAGE_ID=0e8811ef3c92
      - SCENE=LIN
      - DATA_DIR=/mnt/lamas/data
      - OUTPUT_DIR=/output
      - DOCKER_RUN="docker run --runtime=nvidia --shm-size=26G --gpus all -v /mnt/lamas:/mnt/lamas -v output_volume:/output -e DATA_DIR=$DATA_DIR -e MPLCONFIGDIR=$DATA_DIR/matplotlib_config -e OUTPUT_DIR=/output $DOCKER_IMAGE_ID"
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - 5000:5000
    networks:
      - reseau
    volumes:
      - output_volume:/output
      - /mnt/lamas:/mnt/lamas
      - /var/run/docker.sock:/var/run/docker.sock
      - ./python:/app
    command: [ "/app/server.sh" ]
  redis:
    image: redis:6.2
    container_name: redis
    restart: unless-stopped
    networks:
      - reseau
volumes:
  output_volume:
    external: true
networks:
  reseau:
    driver: bridge